The Migration Update
sklauncher/docs pull request #124
Opened 2024-11-04 03:27 UTC by SoyRA

The massive thing is real!

1. I tried to bring everything from the GitHub wiki and the old documentation.
2. I tried to bring everything from the Discord server FAQ channel, as well as the website.
3. I have added new things like the whole Log in topic and questions about security (and conspiracy).

I think everything is relatively good, although I ask for more emphasis on the security part because maybe it's not necessary to mention my repository and even better words could be used.

***

The only thing I didn't finish adding was this, I'll leave it here just in case it's useful in the future:

```mdx
---
slug: /migration-backup
title: Migration backup
unlisted: true
---

:::danger OUTDATED AND UNVERIFIED

The following information is copied from **old wiki / documentation**, so <u>**it's not up-to-date or verified**</u>.\
I've left this as information in case someone else wants to adapt and simplify it to the new documentation.

:::

## CurseForge Launcher

:::info

- On CurseForge you will find a lot of [mods](https://www.curseforge.com/minecraft/mc-mods) for Minecraft, but there are also [modpacks](https://www.curseforge.com/minecraft/modpacks).
    - Installing mods isn't difficult, but modpacks could be difficult if they're not intended for "Extract, copy and paste".
- With this guide you will be able to install the modpacks in three ways:
    - <u>Replace CurseForge Launcher with SKlauncher</u>: You will continue to use *CurseForge Launcher* to download modspacks and stuff, but instead of starting with *Minecraft Launcher* it will use *SKlauncher*.
    - <u>Change the Game Directory</u>: You will use *CurseForge Launcher* to install the modpacks, but you will configure SKlauncher to use that modpack.
    - <u>Move the modpack manually</u>: In some cases they allow you to download the modpack without *CurseForge Launcher* so you install it manually.

:::warning Windows only

- While *CurseForge Launcher* can be used on Linux and Mac OS, this guide is written for Windows.
    - Everything should work anyway, but the guide won't tell you where to go on Linux / Mac OS.

:::

### Replace CurseForge Launcher with SKlauncher
1. Download and install the [CurseForge Launcher](https://download.curseforge.com/).
    * Start it after installation and click on *Minecraft* to install it.
2. Go to [SKlauncher - Downloads](https://skmedix.pl/sklauncher/downloads), download the **Windows (`.exe`)** and rename the file to `minecraft.exe`
    * Be careful, you may not [see the file extension](https://www.tenforums.com/tutorials/62842-hide-show-file-name-extensions-windows-10-a.html) and end up with `minecraft.exe.exe` :P
3. Copy this `minecraft.exe` to paste it in `%USERPROFILE%\curseforge\minecraft\Install` (replacing the original).
    * If you didn't modify the *CurseForge's Minecraft modding folder*, that' s the default path.
4. Done, now CurseForge will launch *SKlauncher* instead of *Minecraft Launcher*.

### Change the Game Directory
1. Download and install the [CurseForge Launcher](https://download.curseforge.com/).
    * Start it after installation and click on *Minecraft* to install it.
2. Install the modpack you want but don't start it (since it will start *Minecraft Launcher*).
3. Download and install the *Mod Loader* (for example: Forge) that the modpack uses.
4. Start *SKlauncher* and edit the *Mod Loader profile* to change the [Game Directory](../../faq/#how-does-game-directory-work) to the path where the modpack is installed.
    * Go to the *My Modpacks* tab in *CurseForge*, right click on the modpack and then *Open Folder* to see where it's installed.
5. Done, after the profile is edited you will be able to start it and play using the modpack.

### Move the modpack manually
- I can't find a modpack that doesn't have its own instructions, if it does NOT have an option for *Minecraft Launcher* (nothing for *CurseForge* or others) then you're likely to have a bad time.
```

2024-12-05 17:30 UTC, skmedix commented
@coderabbitai full review

2025-01-05 15:45 UTC, indexerrowaty requested changes
Sorry for the long wait but here we are. A pull request review!

2025-01-05 15:45 UTC, indexerrowaty commented on docs/troubleshooting/uncategorized.mdx
> +   - Officially there is [Minecraft Forum](https://www.minecraftforum.net/) and [Minecraft Wiki](https://minecraft.fandom.com/wiki/Minecraft_Wiki).
```suggestion
   - Officially there is [Minecraft Forum](https://www.minecraftforum.net/) and [Minecraft Wiki](https://minecraft.wiki/).
```
Don't link to Fandom Minecraft Wiki as it's outdated [due to Fandom being Fandom](https://www.pcgamer.com/official-minecraft-wiki-editors-so-furious-at-fandoms-degraded-functionality-and-popups-theyre-overwhelmingly-voting-to-leave-the-site/). Link to [minecraft.wiki](https://minecraft.wiki/)

2025-01-05 15:45 UTC, indexerrowaty commented on docs/servers/lan-world.mdx
> +1. The host already did everything and you want to connect, then you start the game and go to *Multiplayer*.
```suggestion
1. The host already did everything and you want to connect, so you start the game and go to *Multiplayer*.
```

2025-01-05 15:45 UTC, indexerrowaty commented on docs/servers/lan-world.mdx
> +2. Now choose the *Game Mode* and if you want to *Allow Commands*, then click **Start LAN World**.
```suggestion
1. You want to be the host, so you start the game, fire up the world of choice, press <kbd>ESC</kbd> and click **Open to LAN**.
2. Now configure the server settings to your liking, and then click **Start LAN World**.
```
No need to overcomplicate things.

2025-01-05 15:45 UTC, indexerrowaty commented on docs/servers/lan-world.mdx
> +Honestly you should have already seen the [Modding](/category/modding) guide and have an idea that, depending on the mod you want to install, you'll need to install the required Mod Loader first.
```suggestion
In case you have never installed mods before, you can learn how to do that in the [Modding](/category/modding) guide.
```
This sentence seems rude. I would change it.

2025-01-09 21:29 UTC, indexerrowaty commented on docs/faq/launcher-related.mdx
> +- If the Game Directory is set ([reference image](https://i.imgur.com/Aj4k5hf.png))...
Done!

2025-01-11 19:27 UTC, indexerrowaty approved these changes
Looks good to me! Thanks!

2025-01-11 19:28 UTC, merged